import { chromium } from "playwright-core";
const base = process.env.BASE ?? "http://127.0.0.1:3100";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--no-sandbox"] });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const page = await ctx.newPage();
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push("console: " + m.text()); });
page.on("pageerror", (e) => errors.push("pageerror: " + e.message));
page.on("response", (r) => { if (r.status() >= 500) errors.push(`${r.status()} ${r.url()}`); });
await page.goto(base + "/signup");
await page.fill("#name", "Rishi");
await page.fill("#email", `try${Date.now()}@test.local`);
await page.fill("#password", "password123");
await page.click("button[type=submit]");
await page.waitForURL("**/onboarding", { timeout: 30000 });
await page.getByRole("button", { name: "Continue" }).click();
await page.fill('input[aria-label="Basketball goal"]', "Reliable point guard: 80% free throws");
await page.screenshot({ path: "e2e-shots/_onb2.png" });
await page.getByRole("button", { name: "Continue" }).click();
await page.getByRole("button", { name: "Continue" }).click();
await page.screenshot({ path: "e2e-shots/_onb4.png" });
await page.getByRole("button", { name: "Continue" }).click();
await page.getByRole("button", { name: "Start playing" }).click();
await page.waitForTimeout(4000);
console.log("url:", page.url(), "alert:", await page.locator("[role=alert]").allInnerTexts());
await page.screenshot({ path: "e2e-shots/_onb5.png" });
await page.waitForURL(base + "/", { timeout: 30000 });
await page.waitForSelector('[data-testid="quest"]');
await page.waitForTimeout(1200);
await page.screenshot({ path: "e2e-shots/_dash.png", fullPage: true });
const before = await page.locator('[data-testid="quest"][data-status="open"]').count();
await page.getByRole("button", { name: /^Complete: 100 stationary/ }).first().click();
await page.waitForTimeout(1500);
await page.screenshot({ path: "e2e-shots/_dash_after.png", fullPage: true });
console.log("open quests before:", before, "after:", await page.locator('[data-testid="quest"][data-status="open"]').count());
await page.goto(base + "/quests"); await page.waitForTimeout(600);
await page.screenshot({ path: "e2e-shots/_quests.png", fullPage: true });
await ctx.close();
const m = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const mp = await m.newPage();
await mp.goto(base + "/login"); await mp.fill("#email", "x@x.com");
console.log("errors:", errors);
await browser.close();
