#!/usr/bin/env node
// Bundles supabase/migrations/*.sql into src/db/migrations.generated.ts so the browser can run them.
// The .sql files stay the single source of truth; tests/unit/migrations-bundle.test.ts fails if this file drifts.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dir = path.join(ROOT, "supabase", "migrations");

export function render() {
  const files = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
  const items = files.map((f) => `  { name: ${JSON.stringify(f.replace(/\.sql$/, ""))}, sql: ${JSON.stringify(readFileSync(path.join(dir, f), "utf8"))} },`);
  return `// GENERATED by scripts/gen-sql.mjs from supabase/migrations/*.sql. Do not edit; run \`npm run gen:sql\`.\nexport const MIGRATIONS: { name: string; sql: string }[] = [\n${items.join("\n")}\n];\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(path.join(ROOT, "src", "db", "migrations.generated.ts"), render());
  console.log("wrote src/db/migrations.generated.ts");
}
