#!/usr/bin/env node
// Runs after `next build`. Writes out/sw.js: a service worker that precaches every exported file so the app opens
// and works with no network at all (the database is already on the device). The cache name is a hash of the build,
// so a new deploy installs a new cache and the old one is deleted when the new worker activates.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const OUT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "out");
const SKIP = new Set(["sw.js", "404.html", "_not-found.html"]);

function walk(dir) {
  return readdirSync(dir).flatMap((n) => {
    const p = path.join(dir, n);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

export function precacheList(out = OUT) {
  const urls = [];
  for (const file of walk(out)) {
    const rel = path.relative(out, file).split(path.sep).join("/");
    if (SKIP.has(rel) || rel.startsWith("_not-found")) continue;
    if (rel === "index.html") urls.push("/");
    else if (rel.endsWith(".html")) urls.push("/" + rel.slice(0, -5)); // pages are served at their clean URL
    else urls.push("/" + rel);
  }
  return urls.sort();
}

export function renderSw(urls, version) {
  return `// GENERATED by scripts/gen-sw.mjs. Do not edit.
const CACHE = "level-up-${version}";
const URLS = ${JSON.stringify(urls)};

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // one at a time: the database engine is ~16 MB and a phone on mobile data shouldn't open 150 connections at once
    for (const url of URLS) {
      const res = await fetch(url, { cache: "reload" });
      if (!res.ok || res.redirected) throw new Error("precache failed: " + url);
      await cache.put(url, res);
    }
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key.startsWith("level-up-") && key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return; // e.g. api.anthropic.com is never cached or intercepted
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = (await cache.match(url.pathname)) || (req.mode === "navigate" ? await cache.match("/") : undefined);
    if (hit) return hit;
    try { return await fetch(req); } catch { return Response.error(); }
  })());
});
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const urls = precacheList();
  const fileFor = (u) => (u === "/" ? "index.html" : statSync(path.join(OUT, u.slice(1)), { throwIfNoEntry: false })?.isFile() ? u.slice(1) : u.slice(1) + ".html");
  const h = createHash("sha256");
  for (const u of urls) h.update(u).update(readFileSync(path.join(OUT, fileFor(u))));
  writeFileSync(path.join(OUT, "sw.js"), renderSw(urls, h.digest("hex").slice(0, 12)));
  console.log(`sw.js: ${urls.length} files precached`);
}
